name: 'Monorepo Tagged Split'

on:
    push:
        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

jobs:
    build-matrix:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2.3.4
            -   uses: shivammathur/setup-php@2.15.0
                with:
                    php-version: 7.4
                    coverage: none
            -   name: Install dependencies
                uses: ramsey/composer-install@1.3.0
            -   id: set-packages
                run: echo "::set-output name=packages::$(vendor/bin/monorepo-builder packages-json)"
        outputs:
            packages: ${{ steps.set-packages.outputs.packages }}

    split:
        needs: build-matrix
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.build-matrix.outputs.packages) }}
        steps:
            -
                uses: actions/checkout@v2.3.4
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@v1.1"

            -   uses: TomasVotruba/github-action-monorepo-split@2.0
                env:
                    GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'LongRunning'
                    split-repository-name: '${{ matrix.package }}'
                    user-email: longrunning-bot@users.noreply.github.com
                    user-name: longrunning-bot
                    branch: main
                    tag: ${{ steps.previous_tag.outputs.tag }}
