name: 'Monorepo Split'

on:
    push:
        branches:
            - main

jobs:
    build-matrix:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2.3.4
            -   uses: shivammathur/setup-php@2.15.0
                with:
                    php-version: 7.4
                    coverage: none
            -   name: Install dependencies
                uses: ramsey/composer-install@1.3.0
            -   id: set-packages
                run: echo "::set-output name=packages::$(vendor/bin/monorepo-builder packages-json)"
        outputs:
            packages: ${{ steps.set-packages.outputs.packages }}

    split:
        needs: build-matrix
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.build-matrix.outputs.packages) }}
        steps:
            -   uses: actions/checkout@v2.3.4
            -   uses: TomasVotruba/github-action-monorepo-split@2.0
                env:
                    GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'LongRunning'
                    split-repository-name: '${{ matrix.package }}'
                    user-email: longrunning-bot@users.noreply.github.com
                    user-name: longrunning-bot
                    branch: main
