name: 'Monorepo Split'

on:
    push:
        branches:
            - main
        tags:
            - '*'

jobs:
    build-matrix:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v3
            -   uses: shivammathur/setup-php@2.18.0
                with:
                    php-version: '8.0'
                    coverage: none
                    ini-values: "memory_limit=-1, error_reporting=-1, display_errors=On"
            -   name: Install dependencies
                uses: ramsey/composer-install@2.1.0
            -   id: set-packages
                run: echo "::set-output name=packages::$(vendor/bin/monorepo-builder packages-json)"
        outputs:
            packages: ${{ steps.set-packages.outputs.packages }}

    split:
        needs: build-matrix
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.build-matrix.outputs.packages) }}
        steps:
            -   uses: actions/checkout@v3
            -   if: "!startsWith(github.ref, 'refs/tags/')"
                uses: symplify/monorepo-split-github-action@2.1
                env:
                    GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
                with:
                    package_directory: 'packages/${{ matrix.package }}'
                    repository_organization: 'LongRunning'
                    repository_name: '${{ matrix.package }}'
                    user_email: longrunning-bot@users.noreply.github.com
                    user_name: longrunning-bot
                    branch: main
            -   if: "startsWith(github.ref, 'refs/tags/')"
                uses: symplify/monorepo-split-github-action@2.1
                env:
                    GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}
                    package_directory: 'packages/${{ matrix.package }}'
                    repository_organization: 'LongRunning'
                    repository_name: '${{ matrix.package }}'
                    user_email: longrunning-bot@users.noreply.github.com
                    user_name: longrunning-bot
                    branch: main
